server:
  port: 8080

spring:
  data:
    mongodb:
      host: 192.168.25.135
      port: 27017
      username: Mamba
      password: '1973'
      database: admin
      authentication-database: admin

thread-pool:
  core-pool-size: 10
  max-pool-size: 15
  queue-capacity: 2
  keep-alive-seconds: 200
  thread-name-prefix: 'thread-task'
  shutdown: true


