server:
  port: 8080

spring:
  data:
    mongodb:
      host: 192.168.25.135
      port: 27017
      username: Mamba
      password: '1973'
      database: admin
      authentication-database: admin
